[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["pip install -r requirements.txt", "cd frontend && npm ci && cd .."]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "python start.py"
